name: 'PR CI'

on:
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    name: 'Build and test'

    runs-on: windows-latest

    steps:
    - name: Checkout files
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.x'
    - name: Setup NBGV
      uses: dotnet/nbgv@v0.4
      with:
        toolVersion: 3.5.119
    - name: Restore dependencies
      run: dotnet restore "${{ github.workspace }}/src/SDK.sln"
    - name: Build solution
      run: dotnet build "${{ github.workspace }}/src/SDK.sln" --no-restore -c Release
    - name: Run tests
      run: dotnet test "${{ github.workspace }}/src/SDK.sln" -c Release --filter "TestCategory~Unit|TestCategory~Integration|TestCategory~Functional" --no-build --verbosity normal
    - name: Build samples
      run: ls "${{ github.workspace }}/samples/**/*.sln" | % { dotnet build $_.FullName -c Release }
